//  notes: {
// genderNotes:[],
// pluralHints:[],
// pluralNote:"",
// miscNotes: []
// weakMascNote: 'takes -ns in the genitive singular'}, as i find them. empty notes:{} until i do
//     weakMasculine: false,
//     notes: {}, change to true when i get to them.
// gender hints
// Nouns ending in -e (der Junge,  der Beamte)
// Nouns ending in -ant, -ent, -ist, -ph (der Präsident, der Student, der Journalist)
// A few irregular ones (der Herr, der Nachbar, der Bauer)
// Some nationalities (der Franzose, der Grieche)

// "Der" (masculine) generally goes with endings -ling, -ig, -ner, -smus, -er, -or, -eur, -ent, -ant, -is, -oge and -us, as well as days of the week, months, seasons, monetary units, minerals, and directions.

// "Die" (feminine) generally goes with endings –ung, -ie, -ei, -keit, heit, schaft, –tät, -ik, -(t)ion, -ur, -ar, -ät, -a, -in, -ine, and -euse, as well as numbers, trees, fruits, flowers

// "Das" (neuter) generally goes with endings -chen, -lein, -ment, -tum, -ma, -um, -nis and -ium, as well as colors (when used as nouns), letters, chemical elements

import type { VocabEntry } from './types';

// there are 2000 words coming in.
export const VOCAB_4: VocabEntry[] = [
  {
    id: 1501,
    eng: 'poster',
    article: 'das',
    noun: 'Poster',
    plural: 'die Poster',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1502,
    eng: 'briefcase (soft shell)',
    article: 'die',
    noun: 'Aktentasche',
    plural: 'die Aktentaschen',
    weakMasculine: false,
    notes: {
      miscNote:"Aktentasche can also mean 'portfolio' or 'messenger bag'. It has a soft shell, usually leather, vinyl, or nylon fabric. Aktenkoffer is hard and secure.",
    },
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1503,
    eng: 'identity',
    article: 'die',
    noun: 'Identität',
    plural: 'die Identitäten',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1504,
    eng: 'pavement',
    article: 'der',
    noun: 'Gehweg',
    plural: 'die Gehwege',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1505,
    eng: 'asshole',
    article: 'das',
    noun: 'Arschloch',
    plural: 'die Arschlöcher',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1506,
    eng: 'strap',
    article: 'das',
    noun: 'Band',
    plural: 'die Bänder',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1507,
    eng: 'parlor',
    article: 'der',
    noun: 'Salon',
    plural: 'die Salons',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1508,
    eng: 'harbor',
    article: 'der',
    noun: 'Hafen',
    plural: 'die Häfen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1509,
    eng: 'example',
    article: 'das',
    noun: 'Beispiel',
    plural: 'die Beispiele',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1510,
    eng: 'web',
    article: 'das',
    noun: 'Netz',
    plural: 'die Netze',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1511,
    eng: 'golf',
    article: 'der',
    noun: 'Golf',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1512,
    eng: 'crap',
    article: 'der',
    noun: 'Mist',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1513,
    eng: 'delight',
    article: 'die',
    noun: 'Freude',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1514,
    eng: 'quilt',
    article: 'die',
    noun: 'Steppdecke',
    plural: 'die Steppdecken',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1515,
    eng: 'tax',
    article: 'die',
    noun: 'Steuer',
    plural: 'die Steuern',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1516,
    eng: 'fold',
    article: 'die',
    noun: 'Falte',
    plural: 'die Falten',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1517,
    eng: 'portrait',
    article: 'das',
    noun: 'Porträt',
    plural: 'die Porträts',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1518,
    eng: 'tissue',
    article: 'das',
    noun: 'Gewebe',
    plural: 'die Gewebe',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1519,
    eng: 'belief',
    article: 'der',
    noun: 'Glaube',
    plural: 'die Glauben',
    weakMasculine: true,
    notes: {
      weakMascNote: 'takes -ns in the genitive singular',
    },
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1520,
    eng: 'costume',
    article: 'das',
    noun: 'Kostüm',
    plural: 'die Kostüme',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1521,
    eng: 'measure',
    article: 'das',
    noun: 'Maß',
    plural: 'die Maße',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1522,
    eng: 'carriage',
    article: 'die',
    noun: 'Kutsche',
    plural: 'die Kutschen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1523,
    eng: 'guitar',
    article: 'die',
    noun: 'Gitarre',
    plural: 'die Gitarren',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1524,
    eng: 'knight',
    article: 'der',
    noun: 'Ritter',
    plural: 'die Ritter',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1525,
    eng: 'rank',
    article: 'der',
    noun: 'Rang',
    plural: 'die Ränge',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1526,
    eng: 'major',
    article: 'der',
    noun: 'Major',
    plural: 'die Majore',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1527,
    eng: 'fountain',
    article: 'der',
    noun: 'Brunnen',
    plural: 'die Brunnen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1528,
    eng: 'stall',
    article: 'der',
    noun: 'Stall',
    plural: 'die Ställe',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1529,
    eng: 'load',
    article: 'die',
    noun: 'Ladung',
    plural: 'die Ladungen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1530,
    eng: 'spark',
    article: 'der',
    noun: 'Funke',
    plural: 'die Funken',
    weakMasculine: true,
    notes: {
      weakMascNote: 'takes -ns in the genitive singular',
    },
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1531,
    eng: 'waste',
    article: 'der',
    noun: 'Abfall',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1532,
    eng: 'champagne',
    article: 'der',
    noun: 'Champagner',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1533,
    eng: 'district',
    article: 'der',
    noun: 'Bezirk',
    plural: 'die Bezirke',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1534,
    eng: 'protection',
    article: 'der',
    noun: 'Schutz',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1535,
    eng: 'judgment',
    article: 'das',
    noun: 'Urteil',
    plural: 'die Urteile',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1536,
    eng: 'sympathy',
    article: 'das',
    noun: 'Mitgefühl',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1537,
    eng: 'violet',
    article: 'das',
    noun: 'Veilchen',
    plural: 'die Veilchen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1538,
    eng: 'impact',
    article: 'der',
    noun: 'Aufprall',
    plural: 'die Aufprälle',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1539,
    eng: 'disappointment',
    article: 'die',
    noun: 'Enttäuschung',
    plural: 'die Enttäuschungen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1540,
    eng: 'drinking',
    article: 'das',
    noun: 'Trinken',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1541,
    eng: 'consciousness',
    article: 'das',
    noun: 'Bewusstsein',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1542,
    eng: 'handkerchief',
    article: 'das',
    noun: 'Taschentuch',
    plural: 'die Taschentücher',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1543,
    eng: 'dancing',
    article: 'das',
    noun: 'Tanzen',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1544,
    eng: 'perfume',
    article: 'das',
    noun: 'Parfüm',
    plural: 'die Parfüms',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1545,
    eng: 'network',
    article: 'das',
    noun: 'Netzwerk',
    plural: 'die Netzwerke',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1546,
    eng: 'claim',
    article: 'die',
    noun: 'Forderung',
    plural: 'die Forderungen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1547,
    eng: 'nun',
    article: 'die',
    noun: 'Nonne',
    plural: 'die Nonnen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1548,
    eng: 'crown',
    article: 'die',
    noun: 'Krone',
    plural: 'die Kronen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1549,
    eng: 'railing',
    article: 'das',
    noun: 'Geländer',
    plural: 'die Geländer',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1550,
    eng: 'license',
    article: 'die',
    noun: 'Lizenz',
    plural: 'die Lizenzen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1551,
    eng: 'mercy',
    article: 'die',
    noun: 'Gnade',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1552,
    eng: 'balloon',
    article: 'der',
    noun: 'Ballon',
    plural: 'die Ballons',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1553,
    eng: 'chaos',
    article: 'das',
    noun: 'Chaos',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1554,
    eng: 'fever',
    article: 'das',
    noun: 'Fieber',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1555,
    eng: 'locker',
    article: 'das',
    noun: 'Schließfach',
    plural: 'die Schließfächer',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1556,
    eng: 'session',
    article: 'die',
    noun: 'Sitzung',
    plural: 'die Sitzungen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1557,
    eng: 'burst',
    article: 'der',
    noun: 'Ausbruch',
    plural: 'die Ausbrüche',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1558,
    eng: 'peak',
    article: 'der',
    noun: 'Gipfel',
    plural: 'die Gipfel',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1559,
    eng: 'drum',
    article: 'die',
    noun: 'Trommel',
    plural: 'die Trommeln',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1560,
    eng: 'focus',
    article: 'der',
    noun: 'Fokus',
    plural: 'die Foki',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1561,
    eng: 'frog',
    article: 'der',
    noun: 'Frosch',
    plural: 'die Frösche',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1562,
    eng: 'benefit',
    article: 'der',
    noun: 'Nutzen',
    plural: 'die Nutzen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1563,
    eng: 'remark',
    article: 'die',
    noun: 'Bemerkung',
    plural: 'die Bemerkungen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1564,
    eng: 'tide',
    article: 'die',
    noun: 'Flut',
    plural: 'die Fluten',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1565,
    eng: 'suspicion',
    article: 'der',
    noun: 'Verdacht',
    plural: 'die Verdächte',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1566,
    eng: 'jeep',
    article: 'der',
    noun: 'Jeep',
    plural: 'die Jeeps',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1567,
    eng: 'worry',
    article: 'die',
    noun: 'Sorge',
    plural: 'die Sorgen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1568,
    eng: 'literature',
    article: 'die',
    noun: 'Literatur',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1569,
    eng: 'archer',
    article: 'der',
    noun: 'Bogenschütze',
    plural: 'die Bogenschützen',
    weakMasculine: true,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1570,
    eng: 'household',
    article: 'der',
    noun: 'Haushalt',
    plural: 'die Haushalte',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1571,
    eng: 'powder',
    article: 'das',
    noun: 'Pulver',
    plural: 'die Pulver',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1572,
    eng: 'shepherd',
    article: 'der',
    noun: 'Hirte',
    plural: 'die Hirten',
    weakMasculine: true,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1573,
    eng: 'lens',
    article: 'die',
    noun: 'Linse',
    plural: 'die Linsen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1574,
    eng: 'favorite',
    article: 'der',
    noun: 'Favorit',
    plural: 'die Favoriten',
    weakMasculine: true,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1575,
    eng: 'madame',
    article: 'die',
    noun: 'Dame',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1576,
    eng: 'mansion',
    article: 'die',
    noun: 'Villa',
    plural: 'die Villen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1577,
    eng: 'boom',
    article: 'der',
    noun: 'Boom',
    plural: 'die Booms',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1578,
    eng: 'lace',
    article: 'die',
    noun: 'Spitze',
    plural: 'die Spitzen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1579,
    eng: 'review',
    article: 'die',
    noun: 'Bewertung',
    plural: 'die Bewertungen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1580,
    eng: 'reception',
    article: 'der',
    noun: 'Empfang',
    plural: 'die Empfänge',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1581,
    eng: 'scrap',
    article: 'der',
    noun: 'Schrott',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1582,
    eng: 'bead',
    article: 'die',
    noun: 'Perle',
    plural: 'die Perlen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1583,
    eng: 'glare',
    article: 'das',
    noun: 'Blenden',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1584,
    eng: 'flow',
    article: 'der',
    noun: 'Fluss',
    plural: 'die Flüsse',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1585,
    eng: 'cafe',
    article: 'das',
    noun: 'Café',
    plural: 'die Cafés',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1586,
    eng: 'status',
    article: 'der',
    noun: 'Status',
    plural: 'die Stati',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1587,
    eng: 'pounding',
    article: 'das',
    noun: 'Hämmern',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1588,
    eng: 'rocket',
    article: 'die',
    noun: 'Rakete',
    plural: 'die Raketen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1589,
    eng: 'canyon',
    article: 'die',
    noun: 'Schlucht',
    plural: 'die Schluchten',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1590,
    eng: 'sorrow',
    article: 'die',
    noun: 'Trauer',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1591,
    eng: 'spider',
    article: 'die',
    noun: 'Spinne',
    plural: 'die Spinnen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1592,
    eng: 'blast',
    article: 'die',
    noun: 'Explosion',
    plural: 'die Explosionen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1593,
    eng: 'personality',
    article: 'die',
    noun: 'Persönlichkeit',
    plural: 'die Persönlichkeiten',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1594,
    eng: 'campus',
    article: 'der',
    noun: 'Campus',
    plural: 'die Campi',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1595,
    eng: 'curse',
    article: 'der',
    noun: 'Fluch',
    plural: 'die Flüche',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1596,
    eng: 'staircase',
    article: 'das',
    noun: 'Treppenhaus',
    plural: 'die Treppenhäuser',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1597,
    eng: 'urge',
    article: 'der',
    noun: 'Drang',
    plural: 'die Dränge',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1598,
    eng: 'frustration',
    article: 'die',
    noun: 'Frustration',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1599,
    eng: 'pump',
    article: 'die',
    noun: 'Pumpe',
    plural: 'die Pumpen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1600,
    eng: 'ease',
    article: 'die',
    noun: 'Leichtigkeit',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1601,
    eng: 'count',
    article: 'der',
    noun: 'Graf',
    plural: 'die Grafen',
    weakMasculine: true,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1602,
    eng: 'solution',
    article: 'die',
    noun: 'Lösung',
    plural: 'die Lösungen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1603,
    eng: 'jewelry',
    article: 'der',
    noun: 'Schmuck',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1604,
    eng: 'siren',
    article: 'die',
    noun: 'Sirene',
    plural: 'die Sirenen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1605,
    eng: 'hit',
    article: 'der',
    noun: 'Hit',
    plural: 'die Hits',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1606,
    eng: 'tradition',
    article: 'die',
    noun: 'Tradition',
    plural: 'die Traditionen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1607,
    eng: 'curb',
    article: 'der',
    noun: 'Bordstein',
    plural: 'die Bordsteine',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1608,
    eng: 'variety',
    article: 'die',
    noun: 'Vielfalt',
    plural: 'die Vielfalten',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1609,
    eng: 'pirate',
    article: 'der',
    noun: 'Pirat',
    plural: 'die Piraten',
    weakMasculine: true,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1610,
    eng: 'description',
    article: 'die',
    noun: 'Beschreibung',
    plural: 'die Beschreibungen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1611,
    eng: 'dear',
    article: 'der',
    noun: 'Liebling',
    plural: 'die Lieblinge',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1612,
    eng: 'anxiety',
    article: 'die',
    noun: 'Angst',
    plural: 'die Ängste',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1613,
    eng: 'pitch',
    article: 'die',
    noun: 'Tonhöhe',
    plural: 'die Tonhöhen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1614,
    eng: 'pizza',
    article: 'die',
    noun: 'Pizza',
    plural: 'die Pizzen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1615,
    eng: 'elephant',
    article: 'der',
    noun: 'Elefant',
    plural: 'die Elefanten',
    weakMasculine: true,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1616,
    eng: 'politics',
    article: 'die',
    noun: 'Politik',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1617,
    eng: 'tennis',
    article: 'das',
    noun: 'Tennis',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1618,
    eng: 'hunger',
    article: 'der',
    noun: 'Hunger',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1619,
    eng: 'genius',
    article: 'das',
    noun: 'Genie',
    plural: 'die Genies',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1620,
    eng: 'goat',
    article: 'die',
    noun: 'Ziege',
    plural: 'die Ziegen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1621,
    eng: 'victory',
    article: 'der',
    noun: 'Sieg',
    plural: 'die Siege',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1622,
    eng: 'combination',
    article: 'die',
    noun: 'Kombination',
    plural: 'die Kombinationen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1623,
    eng: 'affiliation',
    article: 'die',
    noun: 'Zugehörigkeit',
    plural: 'die Zugehörigkeiten',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1624,
    eng: 'momma',
    article: 'die',
    noun: 'Mama',
    plural: 'die Mamas',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1625,
    eng: 'cape',
    article: 'das',
    noun: 'Kap',
    plural: 'die Kaps',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1626,
    eng: 'headlight',
    article: 'der',
    noun: 'Scheinwerfer',
    plural: 'die Scheinwerfer',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1627,
    eng: 'governor',
    article: 'der',
    noun: 'Gouverneur',
    plural: 'die Gouverneure',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1628,
    eng: 'oxygen',
    article: 'der',
    noun: 'Sauerstoff',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1629,
    eng: 'bishop',
    article: 'der',
    noun: 'Bischof',
    plural: 'die Bischöfe',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1630,
    eng: 'bundle',
    article: 'das',
    noun: 'Bündel',
    plural: 'die Bündel',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1631,
    eng: 'development',
    article: 'die',
    noun: 'Entwicklung',
    plural: 'die Entwicklungen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1632,
    eng: 'fingernail',
    article: 'der',
    noun: 'Fingernagel',
    plural: 'die Fingernägel',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1633,
    eng: 'score',
    article: 'der',
    noun: 'Punktestand',
    plural: 'die Punktestände',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1634,
    eng: 'mate',
    article: 'der',
    noun: 'Kamerad',
    plural: 'die Kameraden',
    weakMasculine: true,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1635,
    eng: 'rider',
    article: 'der',
    noun: 'Reiter',
    plural: 'die Reiter',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1636,
    eng: 'orbit',
    article: 'die',
    noun: 'Umlaufbahn',
    plural: 'die Umlaufbahnen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1637,
    eng: 'vine',
    article: 'die',
    noun: 'Rebe',
    plural: 'die Reben',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1638,
    eng: 'suite',
    article: 'die',
    noun: 'Suite',
    plural: 'die Suiten',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1639,
    eng: 'bartender',
    article: 'der',
    noun: 'Barkeeper',
    plural: 'die Barkeeper',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1640,
    eng: 'coke',
    article: 'die',
    noun: 'Cola',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1641,
    eng: 'tune',
    article: 'die',
    noun: 'Melodie',
    plural: 'die Melodien',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1642,
    eng: 'glory',
    article: 'der',
    noun: 'Ruhm',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1643,
    eng: 'rabbi',
    article: 'der',
    noun: 'Rabbi',
    plural: 'die Rabbiner',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1644,
    eng: 'surgery',
    article: 'die',
    noun: 'Operation',
    plural: 'die Operationen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1645,
    eng: 'cattle',
    article: 'das',
    noun: 'Rindvieh',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1646,
    eng: 'ritual',
    article: 'das',
    noun: 'Ritual',
    plural: 'die Rituale',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1647,
    eng: 'greeting',
    article: 'der',
    noun: 'Gruß',
    plural: 'die Grüße',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1648,
    eng: 'slice',
    article: 'die',
    noun: 'Scheibe',
    plural: 'die Scheiben',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1649,
    eng: 'homer',
    article: 'der',
    noun: 'Homer',
    plural: 'die Homers',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1650,
    eng: 'fireplace',
    article: 'der',
    noun: 'Kamin',
    plural: 'die Kamine',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1651,
    eng: 'jersey',
    article: 'das',
    noun: 'Trikot',
    plural: 'die Trikots',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1652,
    eng: 'media',
    article: 'die',
    noun: 'Medien',
    plural: 'die Medien',
    weakMasculine: false,
    notes: { pluralNote: 'Exists only in plural form.' },
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1653,
    eng: 'pop',
    article: 'der',
    noun: 'Knall',
    plural: 'die Knalle',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1654,
    eng: 'cargo',
    article: 'die',
    noun: 'Ladung',
    plural: 'die Ladungen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1655,
    eng: 'inn',
    article: 'die',
    noun: 'Herberge',
    plural: 'die Herbergen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1656,
    eng: 'deputy',
    article: 'der',
    noun: 'Stellvertreter',
    plural: 'die Stellvertreter',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1657,
    eng: 'despair',
    article: 'die',
    noun: 'Verzweiflung',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1658,
    eng: 'territory',
    article: 'das',
    noun: 'Gebiet',
    plural: 'die Gebiete',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1659,
    eng: 'punch',
    article: 'der',
    noun: 'Schlag',
    plural: 'die Schläge',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1660,
    eng: 'jazz',
    article: 'der',
    noun: 'Jazz',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1661,
    eng: 'hug',
    article: 'die',
    noun: 'Umarmung',
    plural: 'die Umarmungen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1662,
    eng: 'whistle',
    article: 'die',
    noun: 'Pfeife',
    plural: 'die Pfeifen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1663,
    eng: 'humanity',
    article: 'die',
    noun: 'Menschheit',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1664,
    eng: 'craft',
    article: 'das',
    noun: 'Handwerk',
    plural: 'die Handwerke',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1665,
    eng: 'daylight',
    article: 'das',
    noun: 'Tageslicht',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1666,
    eng: 'worth',
    article: 'der',
    noun: 'Wert',
    plural: 'die Werte',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1667,
    eng: 'slip',
    article: 'die',
    noun: 'Einlage',
    plural: 'die Einlagen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1668,
    eng: 'armor',
    article: 'die',
    noun: 'Rüstung',
    plural: 'die Rüstungen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1669,
    eng: 'backpack',
    article: 'der',
    noun: 'Rucksack',
    plural: 'die Rucksäcke',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1670,
    eng: 'suggestion',
    article: 'der',
    noun: 'Vorschlag',
    plural: 'die Vorschläge',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1671,
    eng: 'den',
    article: 'die',
    noun: 'Höhle',
    plural: 'die Höhlen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1672,
    eng: 'symbol',
    article: 'das',
    noun: 'Symbol',
    plural: 'die Symbole',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1673,
    eng: 'colony',
    article: 'die',
    noun: 'Kolonie',
    plural: 'die Kolonien',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1674,
    eng: 'conclusion',
    article: 'der',
    noun: 'Schluss',
    plural: 'die Schlüsse',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1675,
    eng: 'nostril',
    article: 'das',
    noun: 'Nasenloch',
    plural: 'die Nasenlöcher',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1676,
    eng: 'spear',
    article: 'der',
    noun: 'Speer',
    plural: 'die Speere',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1677,
    eng: 'impulse',
    article: 'der',
    noun: 'Impuls',
    plural: 'die Impulse',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1678,
    eng: 'tomato',
    article: 'die',
    noun: 'Tomate',
    plural: 'die Tomaten',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1679,
    eng: 'calf',
    article: 'das',
    noun: 'Kalb',
    plural: 'die Kälber',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1680,
    eng: 'autumn',
    article: 'der',
    noun: 'Herbst',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1681,
    eng: 'discovery',
    article: 'die',
    noun: 'Entdeckung',
    plural: 'die Entdeckungen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1682,
    eng: 'classroom',
    article: 'das',
    noun: 'Klassenzimmer',
    plural: 'die Klassenzimmer',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1683,
    eng: 'delivery',
    article: 'die',
    noun: 'Lieferung',
    plural: 'die Lieferungen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1684,
    eng: 'spray',
    article: 'das',
    noun: 'Spray',
    plural: 'die Sprays',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1685,
    eng: 'liquid',
    article: 'die',
    noun: 'Flüssigkeit',
    plural: 'die Flüssigkeiten',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1686,
    eng: 'fuel',
    article: 'der',
    noun: 'Treibstoff',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1687,
    eng: 'underwear',
    article: 'die',
    noun: 'Unterwäsche',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1688,
    eng: 'dome',
    article: 'die',
    noun: 'Kuppel',
    plural: 'die Kuppeln',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1689,
    eng: 'population',
    article: 'die',
    noun: 'Bevölkerung',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1690,
    eng: 'affection',
    article: 'die',
    noun: 'Zuneigung',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1691,
    eng: 'religion',
    article: 'die',
    noun: 'Religion',
    plural: 'die Religionen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1692,
    eng: 'singer',
    article: 'der',
    noun: 'Sänger',
    plural: 'die Sänger',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1693,
    eng: 'attendant',
    article: 'der',
    noun: 'Bedienstete',
    plural: 'die Bediensteten',
    weakMasculine: true,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1694,
    eng: 'illusion',
    article: 'die',
    noun: 'Illusion',
    plural: 'die Illusionen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1695,
    eng: 'link',
    article: 'der',
    noun: 'Link',
    plural: 'die Links',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1696,
    eng: 'lounge',
    article: 'die',
    noun: 'Lounge',
    plural: 'die Lounges',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1697,
    eng: 'interior',
    article: 'das',
    noun: 'Innere',
    plural: 'die Innenräume',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1698,
    eng: 'shrug',
    article: 'das',
    noun: 'Achselzucken',
    plural: 'REPLACE',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1699,
    eng: 'zone',
    article: 'die',
    noun: 'Zone',
    plural: 'die Zonen',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },
  {
    id: 1700,
    eng: 'standard',
    article: 'der',
    noun: 'Standard',
    plural: 'die Standards',
    weakMasculine: false,
    notes: {},
    sentences: [
      { de: 'SATZ1', en: 'SENTENCE1', case: 'nom' },
      { de: 'SATZ2', en: 'SENTENCE2', case: 'acc' },
    ],
    completed: false,
  },


];
